# This is an example for local development!
version: "3.7"

services:
  app_server:
    image: shyim/shopware-codespace:php74
    depends_on:
      - mysql
    ports:
      - 80:80
    environment:
      WEB_DOCUMENT_ROOT: /var/www/html/public
    volumes:
       - "./:/var/www/html"
#      - "./config/jwt:/sw6/config/jwt"
#      - "./public/bundles:/sw6/public/bundles"
#      - "./public/media:/sw6/public/media"
#      - "./public/sitemap:/sw6/public/sitemap"
#      - "./public/theme:/sw6/public/theme"
#      - "./public/thumbnail:/sw6/public/thumbnail"
#      - "./var:/sw6/var"

  mysql:
    image: mysql:8.0.19
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: shopware
      MYSQL_USER: shopware
      MYSQL_PASSWORD: shopware
    command: ["mysqld", "--default-authentication-plugin=mysql_native_password"]

#  elasticsearch:
#    image: elastic/elasticsearch:7.9.0
#    environment:
#      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
#      - discovery.type=single-node
